### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by dzeaulfath** [lcucav/criminal-nets#1]
Hi, Icucav i've seen your journal in https://journals.plos.org/ , I need your permission to using these data for my project and I also will give credit for this data. How can i get your permission thourgh email or something else?

**Comment by lcucav** [comment]
Dear Mr. dzeaulfath,

Please feel free to reuse whatever you've found on my GitHub that may help you in your research.
You can just kindly cite my work in your paper and explicitly declare where did you find what you've reused. In the README file you should find the bibitem for the citation plus the link of the original paper DOI.

Thank you for your interest in my research.
For further details, do not hesitate to contact me.

Best regards,
Lucia Cavallaro, PhD

**Comment by lcucav** [comment]
> Hi, Icucav i've seen your journal in https://journals.plos.org/ , I need your permission to using these data for my project and I also will give credit for this data. How can i get your permission thourgh email or something else?

Dear Mr. dzeaulfath,

Please feel free to reuse whatever you've found on my GitHub that may help you in your research.
You can just kindly cite my work in your paper and explicitly declare where did you find what you've reused. In the README file you should find the bibitem for the citation plus the link of the original paper DOI.

You can also have a look here: https://zenodo.org/record/3938818#.YmKYkdNByUk (it's a citable dataset with DOI: 10.5281/zenodo.3938818 )

Thank you for your interest in my research.
For further details, do not hesitate to contact me.

Best regards,
Lucia Cavallaro, PhD

**Comment by lcucav** [comment]
Dear Mr. dzeaulfath,

Please feel free to reuse whatever you've found on my GitHub that may help
you in your research.
You can just kindly cite my work in your paper and explicitly declare where
did you find what you've reused. In the README file you should find the
bibitem for the citation plus the link of the original paper DOI.

Thank you for your interest in my research.
For further details, do not hesitate to contact me.

Best regards,
Lucia Cavallaro, PhD


Il sab 16 apr 2022, 05:42 dzeaulfath ***@***.***> ha scritto:
